services:
  lazyditor:
    image: nginx:alpine
    container_name: lazyditor-frontend
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
